In [2]:
import numpy as np

In [13]:
A=np.array([[1.,0,0,0],[0,1.,0,0],[0,0,1.,0],[0,0,0,1.],[1.,-1.,0,0],[1.,0,-1.,0],[1.,0,0,-1.],[0,1.,-1.,0],[0,1.,0,-1.],[0,0,1.,-1.]])
b=np.array([[2.95],[1.74],[-1.45],[1.32],[1.23],[4.45],[1.61],[3.21],[0.45],[-2.75]])
x=np.linalg.lstsq(A,b)[0].T

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]
 [ 1. -1.  0.  0.]
 [ 1.  0. -1.  0.]
 [ 1.  0.  0. -1.]
 [ 0.  1. -1.  0.]
 [ 0.  1.  0. -1.]
 [ 0.  0.  1. -1.]]
[[ 2.95]
 [ 1.74]
 [-1.45]
 [ 1.32]
 [ 1.23]
 [ 4.45]
 [ 1.61]
 [ 3.21]
 [ 0.45]
 [-2.75]]
[[ 2.96   1.746 -1.46   1.314]]


In [11]:
truevalues = b[0:4]
rel_errors= np.abs((x-truevalues)/x)

[[ 2.95]
 [ 1.74]
 [-1.45]
 [ 1.32]]
[[ 0.01 ]
 [ 0.006]
 [-0.01 ]
 [-0.006]]
[[ 0.00337838]
 [ 0.00343643]
 [ 0.00684932]
 [ 0.00456621]]
