In [101]:
import numpy as np

In [102]:
A=np.array([[1,1,1],[1,2,4],[1,3,9],[1,4,16]])
print (A)

[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]]


In [103]:
G1=np.array([[1,0,0,0],[0,1,0,0],[0,0,1./np.sqrt(2),1./np.sqrt(2)],[0,0,-1./np.sqrt(2),1/np.sqrt(2)]])
print (G1)

[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.          0.70710678  0.70710678]
 [ 0.          0.         -0.70710678  0.70710678]]


In [104]:
A=np.dot(G1,A)
print (A)

[[  1.           1.           1.        ]
 [  1.           2.           4.        ]
 [  1.41421356   4.94974747  17.67766953]
 [  0.           0.70710678   4.94974747]]


In [105]:
c=A[1,0]/np.sqrt(A[1,0]**2 + A[2,0]**2)
s=A[2,0]/np.sqrt(A[1,0]**2 + A[2,0]**2)
G2=np.array([[1,0,0,0],[0,c,s,0],[0,-s,c,0],[0,0,0,1.]])
print (G2)

[[ 1.          0.          0.          0.        ]
 [ 0.          0.57735027  0.81649658  0.        ]
 [ 0.         -0.81649658  0.57735027  0.        ]
 [ 0.          0.          0.          1.        ]]


In [106]:
A=np.dot(G2,A)
print (A)

[[  1.           1.           1.        ]
 [  1.73205081   5.19615242  16.74315781]
 [  0.           1.22474487   6.94022094]
 [  0.           0.70710678   4.94974747]]


In [107]:
c=A[0,0]/np.sqrt(A[0,0]**2 + A[1,0]**2)
s=A[1,0]/np.sqrt(A[0,0]**2 + A[1,0]**2)
G3=np.array([[c,s,0,0],[-s,c,0,0],[0,0,1.,0],[0,0,0,1.]])
print (G3)

[[ 0.5        0.8660254  0.         0.       ]
 [-0.8660254  0.5        0.         0.       ]
 [ 0.         0.         1.         0.       ]
 [ 0.         0.         0.         1.       ]]


In [108]:
A=np.dot(G3,A)
print (A)

[[  2.00000000e+00   5.00000000e+00   1.50000000e+01]
 [  1.11022302e-16   1.73205081e+00   7.50555350e+00]
 [  0.00000000e+00   1.22474487e+00   6.94022094e+00]
 [  0.00000000e+00   7.07106781e-01   4.94974747e+00]]


In [109]:
c=A[2,1]/np.sqrt(A[3,1]**2 + A[2,1]**2)
s=A[3,1]/np.sqrt(A[3,1]**2 + A[2,1]**2)
G4=np.array([[1.,0,0,0],[0,1.,0,0],[0,0,c,s],[0,0,-s,c]])
print (G4)

[[ 1.         0.         0.         0.       ]
 [ 0.         1.         0.         0.       ]
 [ 0.         0.         0.8660254  0.5      ]
 [ 0.         0.        -0.5        0.8660254]]


In [110]:
A=np.dot(G4,A)
print (A)

[[  2.00000000e+00   5.00000000e+00   1.50000000e+01]
 [  1.11022302e-16   1.73205081e+00   7.50555350e+00]
 [  0.00000000e+00   1.41421356e+00   8.48528137e+00]
 [  0.00000000e+00   0.00000000e+00   8.16496581e-01]]


In [111]:
c=A[1,1]/np.sqrt(A[1,1]**2 + A[2,1]**2)
s=A[2,1]/np.sqrt(A[1,1]**2 + A[2,1]**2)
G5=np.array([[1.,0,0,0],[0,c,s,0],[0,-s,c,0],[0,0,0,1.]])
print (G5)

[[ 1.          0.          0.          0.        ]
 [ 0.          0.77459667  0.63245553  0.        ]
 [ 0.         -0.63245553  0.77459667  0.        ]
 [ 0.          0.          0.          1.        ]]


In [112]:
A=np.dot(G5,A)
print (A)

[[  2.00000000e+00   5.00000000e+00   1.50000000e+01]
 [  8.59975057e-17   2.23606798e+00   1.11803399e+01]
 [ -7.02166694e-17   0.00000000e+00   1.82574186e+00]
 [  0.00000000e+00   0.00000000e+00   8.16496581e-01]]


In [113]:
c=A[2,2]/np.sqrt(A[2,2]**2 + A[3,2]**2)
s=A[3,2]/np.sqrt(A[2,2]**2 + A[3,2]**2)
G6=np.array([[1.,0,0,0],[0,1.,0,0],[0,0,c,s],[0,0,-s,c]])
print (G6)

[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.          0.91287093  0.40824829]
 [ 0.          0.         -0.40824829  0.91287093]]


In [114]:
A=np.dot(G6,A)
print (A)

[[  2.00000000e+00   5.00000000e+00   1.50000000e+01]
 [  8.59975057e-17   2.23606798e+00   1.11803399e+01]
 [ -6.40987562e-17   0.00000000e+00   2.00000000e+00]
 [  2.86658352e-17   0.00000000e+00   1.11022302e-16]]


In [115]:
Q=np.dot(G6,np.dot(G5,np.dot(G4,np.dot(G3,np.dot(G2,G1)))))
print (Q.T)

[[ 0.5        -0.67082039  0.5        -0.2236068 ]
 [ 0.5        -0.2236068  -0.5         0.67082039]
 [ 0.5         0.2236068  -0.5        -0.67082039]
 [ 0.5         0.67082039  0.5         0.2236068 ]]


In [99]:
Matrix Q:
   -0.5000    0.6708    0.5000    0.2236
   -0.5000    0.2236   -0.5000   -0.6708
   -0.5000   -0.2236   -0.5000    0.6708
   -0.5000   -0.6708    0.5000   -0.2236

SyntaxError: invalid syntax (<ipython-input-99-875733f5014e>, line 1)

In [132]:
#Householder
B=np.array([[1,1,1],[1,2,4],[1,3,9],[1,4,16]])
v=np.array([[3],[1],[1],[1]])
H=np.identity(4) - (2/np.dot(v.T,v))*np.dot(v,v.T)
print ('H is', H)
X=np.dot(H,B)
print (X)


H is [[-0.5        -0.5        -0.5        -0.5       ]
 [-0.5         0.83333333 -0.16666667 -0.16666667]
 [-0.5        -0.16666667  0.83333333 -0.16666667]
 [-0.5        -0.16666667 -0.16666667  0.83333333]]
[[ -2.00000000e+00  -5.00000000e+00  -1.50000000e+01]
 [  1.11022302e-16   0.00000000e+00  -1.33333333e+00]
 [  5.55111512e-17   1.00000000e+00   3.66666667e+00]
 [  1.11022302e-16   2.00000000e+00   1.06666667e+01]]


In [130]:
S=X[1:,1:]
v2=np.array([[np.sqrt(5)],[1.],[2.]])
H2=np.identity(3)-((2./np.dot(v2.T, v2))*np.dot(v2,v2.T))
Y=np.dot(H2,S)
print (Y)

[[ -2.23606798e+00  -1.11803399e+01]
 [  0.00000000e+00  -7.37048539e-01]
 [ -1.11022302e-16   1.85923625e+00]]


In [129]:
Ha=np.array([[-4./3],[11./3],[32./3]])
V1=np.array([[np.sqrt(5)],[1.],[2.]])
gamma=np.dot(V1.T,Ha)
print (gamma)
print (gamma*2/10)
print ((gamma*2/10)*V1)

[[ 22.01857603]]
[[ 4.40371521]]
[[ 9.84700655]
 [ 4.40371521]
 [ 8.80743041]]


In [118]:
S2=Y[1:,1:]
v3=S2-np.linalg.norm(S2)*np.array([[1],[0]])
H3=np.identity(2)-(2./np.dot(v3.T, v3))*np.dot(v3,v3.T)
z=np.dot(H3,S2)
print (z)

[[  2.00000000e+00]
 [  1.11022302e-16]]


In [119]:
H2=np.hstack((np.array([[0],[0],[0]]),H2))
H2=np.vstack((np.array([1,0,0,0]),H2))
print (H2)

[[  1.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00  -2.22044605e-16  -4.47213595e-01  -8.94427191e-01]
 [  0.00000000e+00  -4.47213595e-01   8.00000000e-01  -4.00000000e-01]
 [  0.00000000e+00  -8.94427191e-01  -4.00000000e-01   2.00000000e-01]]


In [120]:
H3=np.hstack((np.array([[0,0],[0,0]]),H3))
H3=np.vstack((np.array([[1,0,0,0],[0,1,0,0]]),H3))
print (H3)

[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.         -0.36852427  0.92961813]
 [ 0.          0.          0.92961813  0.36852427]]


In [121]:
Q=np.dot(np.dot(H,H2),H3)

In [122]:
print (Q)

[[-0.5         0.67082039  0.5         0.2236068 ]
 [-0.5         0.2236068  -0.5        -0.67082039]
 [-0.5        -0.2236068  -0.5         0.67082039]
 [-0.5        -0.67082039  0.5        -0.2236068 ]]
